create table master_menu
(
    menu_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_order bigint,
    parent_id  bigint,
    menu_code  varchar(50)  not null unique,
    menu_icon  varchar(100),
    menu_name  varchar(100) not null,
    menu_url   varchar(255),
    updated_by bigint,
    created_by bigint,
    created_at timestamp(6),
    updated_at timestamp(6),
    status     varchar(255) check (status in ('ACTIVE', 'INACTIVE'))
);

create table master_role
(
    role_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code   varchar(50)  not null,
    role_name   varchar(100) not null,
    description varchar(255) not null,
    created_at  timestamp(6),
    updated_at  timestamp(6),
    status      varchar(255) check (status in ('ACTIVE', 'INACTIVE'))
);

create table master_unit
(
    unit_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manager_id     bigint,
    parent_unit_id bigint,
    phone          varchar(20),
    unit_code      varchar(50)  not null unique,
    email          varchar(100),
    unit_name      varchar(100) not null,
    address        varchar(255),
    description    varchar(255),
    created_by     bigint,
    updated_by     bigint,
    created_at     timestamp(6),
    updated_at     timestamp(6),
    status         varchar(255) check (status in ('ACTIVE', 'INACTIVE'))
);

create table master_user
(
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id    bigint,
    unit_id    bigint,
    username   varchar(50)  not null unique,
    password   varchar(255) not null,
    email      varchar(100) not null unique,
    phone      varchar(20),
    full_name  varchar(100),
    created_by bigint,
    updated_by bigint,
    created_at timestamp(6),
    updated_at timestamp(6),
    status     varchar(255) check (status in ('ACTIVE', 'INACTIVE'))
);

create table role_menu
(
    role_menu_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id      bigint,
    role_id      bigint,
    created_at   timestamp(6),
    updated_at   timestamp(6),
    status       varchar(255) check (status in ('ACTIVE', 'INACTIVE'))
);

create table user_sessions
(
    session_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       bigint,
    login_at      timestamp(6),
    logout_at     timestamp(6),
    ip_address    varchar(50),
    session_token varchar(255),
    status        varchar(255) check (status in ('ACTIVE', 'INACTIVE')),
    user_agent    varchar(255)
);

alter table if exists master_menu
    add constraint FKbht9xq6n4eruou2qoi6jx6gvg
    foreign key (created_by)
    references master_user;

alter table if exists master_menu
    add constraint FK6u20ntprdr3a9fu88jvkknpva
    foreign key (parent_id)
    references master_menu;

alter table if exists master_menu
    add constraint FK99bvwkgvq2vd2xl7awmxq5a8m
    foreign key (updated_by)
    references master_user;

alter table if exists master_unit
    add constraint FKnyqa7n28622g4xybkm0sx3s3u
    foreign key (created_by)
    references master_user;

alter table if exists master_unit
    add constraint FKtkcup2etyhxs2ephndq13sr6g
    foreign key (manager_id)
    references master_user;

alter table if exists master_unit
    add constraint FKbtj1904ldihbaritl5rtx2ra4
    foreign key (parent_unit_id)
    references master_unit;

alter table if exists master_unit
    add constraint FKeloa8qsmfeny4uhhshmvht7j7
    foreign key (updated_by)
    references master_user;

alter table if exists master_user
    add constraint FK22d9knc1pljdw5jixb12ftcbf
    foreign key (created_by)
    references master_user;

alter table if exists master_user
    add constraint FKf0l0ma00cu4gl6ecdlqu9je1n
    foreign key (role_id)
    references master_role;

alter table if exists master_user
    add constraint FKa4ivaoe5cr352g47ipun26rku
    foreign key (unit_id)
    references master_unit;

alter table if exists master_user
    add constraint FKbbncskstjc0uknu6mgxs07ou1
    foreign key (updated_by)
    references master_user;

alter table if exists role_menu
    add constraint FKcb52efpa6jujusrdogi5f8e98
    foreign key (menu_id)
    references master_menu;

alter table if exists role_menu
    add constraint FKejoa52c0gx2nw6ycgent87evg
    foreign key (role_id)
    references master_role;

alter table if exists user_sessions
    add constraint FKjp8o4c1c6gik0gd9ivdqx9ian
    foreign key (user_id)
    references master_user;
